In [3]:
import numpy as np

### Task 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно.

In [4]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


### Task 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [9]:
a1 = a.reshape(2, 6)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [11]:
a2 = a.reshape(3, 4)
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
a3 = a.reshape(4, 3)
print(a3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [14]:
a4 = a.reshape(6, 2)
print(a4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [16]:
a5 = a.reshape(12, 1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Task 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [17]:
a6 = a.reshape(2, -1)
print(a6)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [18]:
a7 = a.reshape(3, -1)
print(a7)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
a8 = a.reshape(4, -1)
print(a8)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [20]:
a9 = a.reshape(-1, 2)
print(a9)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [21]:
a10 = a.reshape(-1, 1)
print(a10)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Task 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [ ]:
Нет.

### Task 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,
равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [23]:
b = np.random.randn(3, 4)

print(b)
b.size

[[ 1.22633468  0.41335648  0.59992315 -1.53865314]
 [-0.04615163 -0.41877897  0.21556318 -0.42102215]
 [-0.89107447 -0.20026355  0.05238806  0.88344426]]


12

In [25]:
b_to_1D = b.reshape(1, -1)
print(b_to_1D)
b_to_1D.size

[[ 1.22633468  0.41335648  0.59992315 -1.53865314 -0.04615163 -0.41877897
   0.21556318 -0.42102215 -0.89107447 -0.20026355  0.05238806  0.88344426]]


12

### Task 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с
интервалом 2.

In [29]:
a = np.arange(20, 0, -2)
print(a)
a.shape

[20 18 16 14 12 10  8  6  4  2]


(10,)

### Task 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1
невключительно с интервалом 2. В чем разница между массивами a и b?

In [31]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)
b.shape

[[20 18 16 14 12 10  8  6  4  2]]


(1, 10)

Массив а является одномерным, а массив b - двумерный.

### Task 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого
больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [42]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size
print(v)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Task 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [43]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [53]:
B = A.dot(At)
print(B)

print(f'Матрица В имеет размер: {B.size}')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица В имеет размер: 16


In [51]:
d = np.linalg.det(B)

print(d)

0.0


In [ ]:
Обратную матрицу вычислить нельзя, так как определитель матрицы В равен нулю.

### Task 10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [62]:
np.random.seed(42)
print('Случайное часло с seed = 42:', np.random.random())

Случайное часло с seed = 42: 0.3745401188473625


### Task 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [70]:
c = np.random.randint(0, 16, 16)

print(c)

[ 0 10 10 14  9 15 11 11 15 14 13 13 14 13  2 11]


### Task 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [72]:
C = c.reshape(4, 4)
print(C)

[[ 0 10 10 14]
 [ 9 15 11 11]
 [15 14 13 13]
 [14 13  2 11]]


In [74]:
D = B + C * 10
print(D)

[[  5 114 123 172]
 [104 200 196 232]
 [173 226 279 342]
 [172 252 232 412]]


In [76]:
print(f'Определитель матрицы D равен: {np.linalg.det(D)}')

Определитель матрицы D равен: -120635999.9999998


In [77]:
print(f'Ранг матрицы D равен: {np.linalg.matrix_rank(D)}')

Ранг матрицы D равен: 4


In [83]:
D_inv = np.linalg.inv(D)
print('Обратная матрица для D')
print(D_inv)

Обратная матрица для D
[[-0.01339302  0.00109453  0.00322424  0.00229848]
 [-0.00463742  0.02241553 -0.01555025  0.00222189]
 [ 0.00558639 -0.00474452  0.01346994 -0.01084187]
 [ 0.00528201 -0.01149574  0.00058026  0.00621373]]


### Task 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [86]:
D_inv[(D_inv < 0)] = 0
D_inv[(D_inv > 0)] = 1

print(D_inv)

[[0. 1. 1. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]]


In [88]:
E = np.where(D_inv, B, C)
print(E)

[[  0  14  23  32]
 [  9  50  11 122]
 [ 23  14 149  13]
 [ 32  13 212 302]]
